import React, {useState} from 'react'
import styled from 'styled-components'
import './Endgame.css'
import img1 from '../../media/Data/endgame/1.png'
import img2 from '../../media/Data/endgame/2.png'
import img3 from '../../media/Data/endgame/3.png'
import img4 from '../../media/Data/endgame/4.png'
import img5 from '../../media/Data/endgame/5.png'
import img6 from '../../media/Data/endgame/6.png'
import img7 from '../../media/Data/endgame/7.png'
import img8 from '../../media/Data/endgame/8.png'
import img9 from '../../media/Data/endgame/9.png'
import img10 from '../../media/Data/endgame/10.png'
import img11 from '../../media/Data/endgame/11.png'
import img12 from '../../media/Data/endgame/12.png'
import img13 from '../../media/Data/endgame/13.png'
import img14 from '../../media/Data/endgame/14.png'
import img15 from '../../media/Data/endgame/15.png'
import img16 from '../../media/Data/endgame/16.png'
import img17 from '../../media/Data/endgame/17.png'
import img18 from '../../media/Data/endgame/18.png'
import img19 from '../../media/Data/endgame/19.png'
import img20 from '../../media/Data/endgame/20.png'
import img21 from '../../media/Data/endgame/21.png'
import img22 from '../../media/Data/endgame/22.png'
import img23 from '../../media/Data/endgame/23.png'
import img24 from '../../media/Data/endgame/24.png'
import img25 from '../../media/Data/endgame/25.png'
import img26 from '../../media/Data/endgame/26.png'
import img27 from '../../media/Data/endgame/27.png'
import img28 from '../../media/Data/endgame/28.png'
import img29 from '../../media/Data/endgame/29.png'
import img30 from '../../media/Data/endgame/30.png'
import img31 from '../../media/Data/endgame/31.png'
import img32 from '../../media/Data/endgame/32.png'
import img33 from '../../media/Data/endgame/33.png'
import img34 from '../../media/Data/endgame/34.png'
import img35 from '../../media/Data/endgame/35.png'
import img36 from '../../media/Data/endgame/36.png'
import img37 from '../../media/Data/endgame/37.png'
import img38 from '../../media/Data/endgame/38.png'
import img39 from '../../media/Data/endgame/39.png'
import img40 from '../../media/Data/endgame/40.png'
import img41 from '../../media/Data/endgame/41.png'
import img42 from '../../media/Data/endgame/42.png'
import img43 from '../../media/Data/endgame/43.png'
import img44 from '../../media/Data/endgame/44.png'
import img45 from '../../media/Data/endgame/45.png'
import img46 from '../../media/Data/endgame/46.png'
import img47 from '../../media/Data/endgame/47.png'
import img48 from '../../media/Data/endgame/48.png'
import img49 from '../../media/Data/endgame/49.png'
import img50 from '../../media/Data/endgame/50.png'
import img51 from '../../media/Data/endgame/51.png'
import img52 from '../../media/Data/endgame/52.png'
import img53 from '../../media/Data/endgame/53.png'
import img54 from '../../media/Data/endgame/54.png'
import img55 from '../../media/Data/endgame/55.png'
import img56 from '../../media/Data/endgame/56.png'
import img57 from '../../media/Data/endgame/57.png'
import img58 from '../../media/Data/endgame/58.png'
import img59 from '../../media/Data/endgame/59.png'
import img60 from '../../media/Data/endgame/60.png'
import img61 from '../../media/Data/endgame/61.png'
import img62 from '../../media/Data/endgame/62.png'
import img63 from '../../media/Data/endgame/63.png'
import img64 from '../../media/Data/endgame/64.png'
import img65 from '../../media/Data/endgame/65.png'
import img66 from '../../media/Data/endgame/66.png'
import img67 from '../../media/Data/endgame/67.png'
import img68 from '../../media/Data/endgame/68.png'
import img69 from '../../media/Data/endgame/69.png'
import img70 from '../../media/Data/endgame/70.png'
import img71 from '../../media/Data/endgame/71.png'
import img72 from '../../media/Data/endgame/72.png'
import img73 from '../../media/Data/endgame/73.png'
import img74 from '../../media/Data/endgame/74.png'
import img75 from '../../media/Data/endgame/75.png'
import img76 from '../../media/Data/endgame/76.png'
import img77 from '../../media/Data/endgame/77.png'
import img78 from '../../media/Data/endgame/78.png'
const Endgame = () => {
    const [scrollPos, setScrollPos] = useState(1)
    // const EndgameContainer = styled.div`
    // `
    const scrollEndgame = e =>{
        if(e.deltaY < 0 && scrollPos >1){
            setScrollPos(scrollPos-1)
        } else if(e.deltaY > 0 && scrollPos < 97) {
            setScrollPos(scrollPos+1)
        };
    }
    return (
        <div onWheel={scrollEndgame} className={`EndgameContainer img${scrollPos}`} style={scrollPos == 97 ? {display:"none"} : {display:"inherit"}}>
            
        </div>
    )
}

export default Endgame
